CREATE TABLE IF NOT EXISTS tri_configs (
  user_id INT NOT NULL PRIMARY KEY,
  json TEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
